import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Auth from "@/components/auth/Auth";

import '@aws-amplify/ui-react/styles.css';

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import {isAuthenticated} from "@/utils/amplify-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Title Listing",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar isSignedIn={await isAuthenticated()} />
        <Auth>
          {children}
        </Auth>
      </body>
    </html>
  );
}
